language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - tox
    - coverage run -m py.test
    - coverage report -m

notifications:
  email: false

after_success:
  - coveralls